### PR TITLE
Bunch of clippy lints that are also formatted

### PR DESCRIPTION
**Pull request by wcampbell0x2a**
I'll admit I only ran the clippy --fmt and didn't test it.

### CODE REVIEW

**Comment by Brian-Catcow-B** [comment]
f

**Comment by wcampbell0x2a** [comment]
> f

I'll try it in smaller patches

**Comment by Brian-Catcow-B** [comment]
wait, if you pull in the `final-prenetcode-update` code and do `rustup default 1.47.0`, then it might work. I'm gonna try building with 1.47.0 and see if it crashes at all

**Comment by Brian-Catcow-B** [comment]
clippi-go-rip

**Pull request closed without merging**
